config/routes.rb
Casadasmatas::Application.routes.draw do

  match "produtos" => 'products#index', as: :products
  match "produtos/:id" => 'products#show', as: :product

  match "blog/postagem/:id" => 'posts#show', as: :post
  match "blog" => 'posts#index', as: :posts

  match "paginas/:id" => 'pages#show', as: :page

  match 'fale-conosco' => 'talk_to_us#index', as: :talk_to_us
  match 'fale-conosco/enviar' => 'talk_to_us#send_mail', as: :send_talk_to_us, via: :post

  match 'adicionar-ao-carrinho/:id' => 'orders#add_to_cart', as: :add_to_cart

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  mount Ckeditor::Engine => '/ckeditor'

  

  root :to => 'welcome#index'

end

app/models/banner.rb
# encoding: utf-8
class Banner < ActiveRecord::Base
  MEDIUM, BIG = 'Banner superior', 'Banner médio'
  scope :bigs, where(localization: BIG)
  scope :mediums, where(localization: MEDIUM)
  attr_accessible :description, :image, :position, :title, :localization, :url
   has_attached_file :image, styles: { thumb: "75x75#", normal: '300x300#', big: "940x500#", medium: "300x259#"},
                    default_style: :normal
  validates :image, attachment_presence: true
  validates_presence_of :title, :localization, :description, :url

  def localization_enum
    [Banner::BIG,Banner::MEDIUM]
  end
end

app/models/category_post.rb
class CategoryPost < ActiveRecord::Base
  attr_accessible :name
  validates :name, presence: true, uniqueness: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :client_email, :client_name, :finished, :total, :order_products_attributes
  attr_protected :total
  
  has_many :order_products, dependent: :destroy
  accepts_nested_attributes_for :order_products
  validates_presence_of :client_name, :client_email
  # has_many :order_histories, dependent: :destroy
  def name
    return nil if self.new_record?
    "#{self.client_name} #{I18n.l(self.created_at)} | #{self.total.to_f.real_contabil}"
  end
end

app/models/order_history.rb
class OrderHistory < ActiveRecord::Base
  belongs_to :order
  attr_accessible :informations, :order_id
  validates_presence_of :informations, :order_id

  def name
    return nil if self.new_record?
    "Criado em: #{I18n.l(self.created_at)} | Pedido: #{self.order.name rescue '-'}"
  end
end

app/models/order_product.rb
class OrderProduct < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  attr_accessible :price, :quantity, :product_id
  validates_presence_of :product_id, :price, :quantity
  validates_numericality_of :quantity, greater_than: 0
  validates_numericality_of :price, greater_than: 0

  def name
    "#{self.product.name rescue '-'} | Pedido: #{self.order.name rescue '-'}"
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :content, :title, :url
  validates :title, presence: true, uniqueness: true
  validates :url, presence: true, uniqueness: true
  validates :content, presence: true
end

app/models/parameter.rb
class Parameter < ActiveRecord::Base
  attr_accessible :contact_to, :pagseguro_email, :pagseguro_token
  validates_presence_of :contact_to, :pagseguro_email, :pagseguro_token
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category_post
  attr_accessible :content, :title, :category_post_id, :short_description
  validates :title, presence: true
  validates :short_description, presence: true
  validates :content, presence: true
  validates :category_post_id, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :price, :special_price, :weight, :short_description, 
  :product_images_attributes

  validates_presence_of :description, :name, :short_description
  validates_numericality_of :price, :weight, greater_than: 0
  validates_numericality_of :special_price, greater_than: 0, allow_nil: true

  has_many :product_images, dependent: :destroy
  accepts_nested_attributes_for :product_images

  def image
    self.product_images.order('principal DESC').first.image
  end
end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  belongs_to :product
  attr_accessible :image, :principal
  has_attached_file :image, styles: { thumb: "70x70#", normal: "300x259#", medium: '200x150#', big: '900x500#'},
                    default_style: :thumb
  validates :image, attachment_presence: true

  def name
    "#{self.image_file_name} | Produto: #{self.product.name rescue '-'}"
  end
end

app/models/talk_to_us.rb
class TalkToUs
  include ActiveAttr::Model
  include ActiveAttr::TypecastedAttributes
  
  attribute :name
  attribute :email
  attribute :message
  validates_presence_of :name, :email, :message
  
  attr_accessible :name, :email, :message

  def send_mail
    return false unless self.valid?

    MailSender.talk_to_us(self.name,self.email,self.message).deliver
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.where(url: params[:id]).last
    raise unless @page
  rescue
    redirect_to root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def month_name(month)
    I18n.t('date.abbr_month_names')[month]
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/talk_to_us_helper.rb
module TalkToUsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def big_banners
    Banner.bigs.limit(4)
  end

  def medium_banners
    Banner.mediums.limit(3)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Café das Matas</title>
  <meta charset="utf-8">
  <meta name="description" content="Your description">
  <meta name="keywords" content="Your keywords">
  <meta name="author" content="Your name">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <!--[if lt IE 8]>
    <div style=' clear: both; text-align:center; position: relative;'>
    <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode"><img src="http://storage.ie6countdown.com/assets/100//assets/template/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." /></a>
    </div>
    <![endif]-->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "template/html5" %>
    <%= stylesheet_link_tag    "template/ie", :media => "all" %>
    <![endif]-->
    <%= csrf_meta_tags %>
  </head>
  <body id="page1">
    <div class="bg">
      <!--==============================header=================================-->
      <header>
        <%= render partial: 'shared/header' %>
      </header>

      <!--==============================content================================-->
      <section id="content">
        <div class="main">
          <div class="container_12">
            <%= yield -%>
          </div>
        </div>
      </section>

      <!--==============================footer=================================-->
      <footer>
        <%= render partial: 'shared/footer' %>
      </footer>
    </div>
  </body>
</html>

app/views/mail_sender/talk_to_us.text.erb
Nome: <%= @name %>

Email: <%= @email %>

Mensagem: 

<%= @message %>

app/views/pages/show.html.erb
<div class="wrapper p21 pr">
  <article class="grid_12">
    <h2 class="main_h2 p10"><%= @page.title %></h2>
    <%= @page.content.html_safe %>
                   
  </article>
</div>

app/views/shared/_footer.erb
<div class="main">
  <div class="page-foot">
    <span>Café das Matas</span><div class="inner-foot">&copy; 2012 | desenvolvidor por <%= mail_to 'rodrigo@rtoledo.inf.br', 'rodrigo toledo', encode: 'hex' %></div>
  </div>            
  <ul class="social-links">                  
    <li><a href="#" class="link-1" title="Twitter"></a></li>
    <li><a href="#" class="link-2" title="Facebook"></a></li>
    <li><a href="#" class="link-5" title="Google+"></a></li>
  </ul>
  <span class="text6">Nos encontre em:</span>
  <div class="foot"><!-- {%FOOTER_LINK} --></div>
  <div class="clear"></div>
</div>

app/views/shared/_header.erb
<div class="main">
  <div class="head-box2">
    <a class="logo" href="index.html">logo</a><span class="text1">café, cultura e negócios</span>
    <div class="head-box1">
      <!-- <form id="search-form" method="get" enctype="multipart/form-data">
        <fieldset>
          <div class="search-form">         
            <input type="text" name="search" />
            <a href="#" onClick="document.getElementById('search-form').submit()"></a>                  
          </div>
        </fieldset>
      </form> -->
      <div class="clear"></div>
    </div>
    <div class="clear"></div>
  </div>
  <%= render partial: 'shared/top_menu' %>
</div>
<%= render partial: 'welcome/banners' if current_page?(root_path) %>

app/views/shared/_top_menu.erb
<nav>
  <ul class="sf-menu">
    <li class="<%='active' if current_page?(root_path) %>"><a href="<%=root_path%>"><strong>Página<i>inicial</i></strong></a></li>
    <li><a href="index-1.html"><strong>Minas Coffee<i>about export</i></strong></a>
      <ul>
        <li><a href="more.html">History</a></li>
        <li><a href="more.html">News</a>
          <ul>
            <li><a href="more.html">Latest</a></li>
            <li><a href="more.html">Archive</a></li>
          </ul>
        </li>
        <li><a href="more.html">Resources</a></li>
      </ul>
    </li>
    <li class="<%='active' if controller.controller_name == 'products' %>"><a href="<%= products_path %>"><strong>Produtos<i>compre aqui</i></strong></a></li>
    <li class="<%='active' if current_page?(page_path('conheca-nos')) %>"><a href="<%= page_path('conheca-nos') %>"><strong>Conheça-nos<i>fique a vontade</i></strong></a></li>
    <li class="<%='active' if controller.controller_name == 'posts' %>"><a href="<%= posts_path %>"><strong>blog<i>novidades</i></strong></a></li>
    <li class="last2 <%='active' if current_page?(talk_to_us_path) %>"><a href="<%= talk_to_us_path %>"><strong>Fale conosco<i>contato direto</i></strong></a></li>
  </ul>
  <div class="clear"></div>
</nav>