config/routes.rb
Casadasmatas::Application.routes.draw do

  match "produtos" => 'products#index', as: :products
  match "produtos/:id" => 'products#show', as: :product

  match "blog/postagem/:id" => 'posts#show', as: :post
  match "blog" => 'posts#index', as: :posts

  match "paginas/:id" => 'pages#show', as: :page

  match 'fale-conosco' => 'talk_to_us#index', as: :talk_to_us
  match 'fale-conosco/enviar' => 'talk_to_us#send_mail', as: :send_talk_to_us, via: :post

  match 'adicionar-ao-carrinho/:id' => 'orders#add_to_cart', as: :add_to_cart

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  mount Ckeditor::Engine => '/ckeditor'

  

  root :to => 'welcome#index'

end

app/models/banner.rb
# encoding: utf-8
class Banner < ActiveRecord::Base
  MEDIUM, BIG = 'Banner superior', 'Banner médio'
  scope :bigs, where(localization: BIG)
  scope :mediums, where(localization: MEDIUM)
  attr_accessible :description, :image, :position, :title, :localization, :url
   has_attached_file :image, styles: { thumb: "75x75#", normal: '300x300#', big: "940x500#", medium: "300x259#"},
                    default_style: :normal
  validates :image, attachment_presence: true
  validates_presence_of :title, :localization, :description, :url

  def localization_enum
    [Banner::BIG,Banner::MEDIUM]
  end
end

app/models/category_post.rb
class CategoryPost < ActiveRecord::Base
  attr_accessible :name
  validates :name, presence: true, uniqueness: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :client_email, :client_name, :finished, :total, :order_products_attributes
  attr_protected :total
  
  has_many :order_products, dependent: :destroy
  accepts_nested_attributes_for :order_products
  validates_presence_of :client_name, :client_email
  # has_many :order_histories, dependent: :destroy
  def name
    return nil if self.new_record?
    "#{self.client_name} #{I18n.l(self.created_at)} | #{self.total.to_f.real_contabil}"
  end
end

app/models/order_history.rb
class OrderHistory < ActiveRecord::Base
  belongs_to :order
  attr_accessible :informations, :order_id
  validates_presence_of :informations, :order_id

  def name
    return nil if self.new_record?
    "Criado em: #{I18n.l(self.created_at)} | Pedido: #{self.order.name rescue '-'}"
  end
end

app/models/order_product.rb
class OrderProduct < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  attr_accessible :price, :quantity, :product_id
  validates_presence_of :product_id, :price, :quantity
  validates_numericality_of :quantity, greater_than: 0
  validates_numericality_of :price, greater_than: 0

  def name
    "#{self.product.name rescue '-'} | Pedido: #{self.order.name rescue '-'}"
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :content, :title, :url
  validates :title, presence: true, uniqueness: true
  validates :url, presence: true, uniqueness: true
  validates :content, presence: true
end

app/models/parameter.rb
class Parameter < ActiveRecord::Base
  attr_accessible :contact_to, :pagseguro_email, :pagseguro_token
  validates_presence_of :contact_to, :pagseguro_email, :pagseguro_token
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category_post
  attr_accessible :content, :title, :category_post_id, :short_description
  validates :title, presence: true
  validates :short_description, presence: true
  validates :content, presence: true
  validates :category_post_id, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :price, :special_price, :weight, :short_description, 
  :product_images_attributes

  validates_presence_of :description, :name, :short_description
  validates_numericality_of :price, :weight, greater_than: 0
  validates_numericality_of :special_price, greater_than: 0, allow_nil: true

  has_many :product_images, dependent: :destroy
  accepts_nested_attributes_for :product_images

  def image
    self.product_images.order('principal DESC').first.image
  end
end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  belongs_to :product
  attr_accessible :image, :principal
  has_attached_file :image, styles: { thumb: "70x70#", normal: "300x259#", medium: '200x150#', big: '900x500#'},
                    default_style: :thumb
  validates :image, attachment_presence: true

  def name
    "#{self.image_file_name} | Produto: #{self.product.name rescue '-'}"
  end
end

app/models/talk_to_us.rb
class TalkToUs
  include ActiveAttr::Model
  include ActiveAttr::TypecastedAttributes
  
  attribute :name
  attribute :email
  attribute :message
  validates_presence_of :name, :email, :message
  
  attr_accessible :name, :email, :message

  def send_mail
    return false unless self.valid?

    MailSender.talk_to_us(self.name,self.email,self.message).deliver
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.where(url: params[:id]).last
    raise unless @page
  rescue
    redirect_to root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.limit(6)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
# encoding: utf-8
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Ops, ocorreu um erro")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Verifique a lista de erros abaixo e faça as correções.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def month_name(month)
    I18n.t('date.abbr_month_names')[month]
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/talk_to_us_helper.rb
module TalkToUsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def big_banners
    Banner.bigs.limit(4)
  end

  def medium_banners
    Banner.mediums.limit(3)
  end
end

app/views/welcome/_banners.erb
<div class="slider-bg">
  <div class="slider">
    <ul class="items">
      <%= big_banners.each do |banner| %>
      <li><%= image_tag banner.image.url(:big) %>
        <div class="banner">
          <div class="banner-head"><%= banner.title %></div>
          <div class="banner-box">
            <%= banner.description.html_safe %>
          </div>
        </div>
      </li>
      <% end -%>
    </ul>
    <a href="#" class="prev"></a><a href="#" class="next"></a> 
  </div>                  
</div>

app/views/welcome/index.html.erb
<div class="wrapper p8">
  <article class="grid_12">
    <h2 class="main_h2 p10">Veja o que temos pra você</h2>
    <% medium_banners.each do |banner| %>
    <article class="grid_4 <%=cycle('alpha','','omega')%>">
      <div class="page1-box1">
        <figure class="page1-img1"><%= image_tag banner.image.url(:medium) %></figure>
        <strong><%= banner.title %></strong>
        <p class="p7"><%= banner.description %></p>
        <a class="button2" href="<%= banner.url %>">mais...</a>
        <div class="clear"></div>
      </div>
    </article>
    <% end -%>
  </article>
</div>
<div class="wrapper margin-bot">
  <article class="grid_5">
    <h2 class="main_h2">Not brazilian?</h2>
    <div class="page1-box4">
     <p>You work with coffee or have an interest in our work? Know then the Minas Coffee Export.</p>
     <ul class="list2">
      <li><a href="#">Consulting and exchange experiences</a></li>
      <li><a href="#">Coffee exports</a></li>
      <li><a href="#">You know the beauty of the forests of Minas Gerais</a></li>
    </ul>
  </div>
</article>
<article class="grid_6 push_1">
  <h2 class="main_h2">últimas notícias</h2>
  <div class="posrel">
    <div class="carousel">
      <ul>
        <% @posts.in_groups_of(2,false).each do |post_grouped| %>
        <li>
          <% post_grouped.each do |post| %>
          <div class="page1-box5 <%= cycle('','p11')%>">
            <div class="inner1">
              <%= post.created_at.day %>
              <span><%= month_name post.created_at.month %></span>
            </div>
            <div class="extra-wrap">
              <a class="link2" href="<%= post_path post %>"><%= post.title %></a>
              <p><%= post.short_description %></p>
            </div>
          </div>
          <% end -%>
          
        </li>
        <% end -%>
      </ul>
    </div>
    <a href="#" class=" car-button next1" data-type="prevPage"></a>
    <a href="#" class="car-button prev1" data-type="nextPage"></a>
  </div>
</article>
</div>
<!-- <div class="wrapper">
  <article class="grid_12">
    <h2 class="main_h2">parceiros</h2>
    <a href="more.html"><figure class="page1-img2"><img src="/assets/template/page1-img4.jpg" alt=""></figure></a>
    <a href="more.html"><figure class="page1-img2"><img src="/assets/template/page1-img5.jpg" alt=""></figure></a>
    <a href="more.html"><figure class="page1-img2"><img src="/assets/template/page1-img6.jpg" alt=""></figure></a>
    <a href="more.html"> <figure class="page1-img2 p12"><img src="/assets/template/page1-img7.jpg" alt=""></figure></a>
  </article>
</div> -->